---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  - sudo modprobe ip6_tables
  - pip install molecule docker yamllint ansible-lint testinfra

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
