---
# tasks file for ansible-role-quassel-core
- name: Add Quassel PPA
  apt_repository:
    repo: "ppa:mamarley/quassel"
  when: quasselcore_use_ppa and ansible_distribution == 'Ubuntu'

- name: Install quassel-core
  apt:
    name: quassel-core
    state: present

- name: place our systemctl service
  copy:
    src: quasselcore.service
    dest: /lib/systemd/system/quasselcore.service
    owner: root
    group: root
    mode: 0644
  notify: restart quassel-core

- name: Enable quassel-core on boot
  service:
    name: quasselcore
    state: started
    enabled: true
  when: quasselcore_systemd_enabled == true

- name: Disable quassel-core on boot
  service:
    name: quasselcore
    state: stopped
    enabled: false
  when: quasselcore_systemd_enabled == false

- name: Setup ufw firewall rule
  ufw:
    rule: allow
    port: "4242"
    proto: tcp
  when: quasselcore_setup_ufw
